version: "3.4"
services:
  webserver:
    build:
      context: ./app
    ports:
      - "80:5000"
    links:
      - mysqldb
    restart: 'always'
    volumes:
      - ./app/server:/server
  mysqldb:
    image: mysql:latest
    restart: 'always'
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Jvdf76sFWGYZHWUD
      MYSQL_DATABASE: squadmarker
      MYSQL_USER: me
      MYSQL_PASSWORD: Jvdf76sFWGYZHWUD
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'Phpmyadmin'
    links:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
    ports:
      - '800:80'